const root1 = document.querySelector('[data-key="order1"]')
const biscuits1 = root1.querySelector(".biscuits .count").textContent = root1.getAttribute("data-biscuits")
const donuts1 = root1.querySelector(".donuts .count").textContent = root1.getAttribute("data-donuts")
const pancakes1 = root1.querySelector(".pancakes .count").textContent = root1.getAttribute("data-pancakes")
const status1 = root1.querySelector(".status dd").textContent = root1.getAttribute("data-delivered")

const root2 = document.querySelector('[data-key="order2"]')
const biscuits2 = root2.querySelector(".biscuits .count").textContent = root2.getAttribute("data-biscuits")
const donuts2 = root2.querySelector(".donuts .count").textContent = root2.getAttribute("data-donuts")
const pancakes2 = root2.querySelector(".pancakes .count").textContent = root2.getAttribute("data-pancakes")
const status2 = root2.querySelector(".status dd").textContent = root2.getAttribute("data-delivered")

const root3 = document.querySelector('[data-key="order3"]')
const biscuits3 = root3.querySelector(".biscuits .count").textContent = root3.getAttribute("data-biscuits")
const donuts3 = root3.querySelector(".donuts .count").textContent = root3.getAttribute("data-donuts")
const pancakes3 = root3.querySelector(".pancakes .count").textContent = root3.getAttribute("data-pancakes")
const status3 = root3.querySelector(".status dd").textContent = root3.getAttribute("data-delivered")